# Generated by Django 4.2 on 2023-06-05 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='editor_image/', verbose_name='Avatar')),
                ('position', models.CharField(max_length=120, verbose_name='Lavozimi')),
                ('bio_short', models.CharField(blank=True, max_length=120, null=True, verbose_name='Bio')),
                ('bio_long', models.TextField(blank=True, max_length=3000, null=True)),
                ('editor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tahrirlovchi')),
            ],
            options={
                'verbose_name': 'Tahrirlovchi',
                'verbose_name_plural': 'Tahrirlovchilar',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Til',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=250, verbose_name='Fayl url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referens',
                'verbose_name_plural': 'Referenslar',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journal_images/', verbose_name='Rasmi')),
                ('description', models.CharField(max_length=250, verbose_name='Tavsif')),
                ('volume', models.IntegerField(default=1)),
                ('isbn', models.CharField(max_length=50, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('copyright', models.CharField(max_length=250, verbose_name='Litsenziya')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.language')),
                ('main_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.editor')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnallar',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(max_length=50, verbose_name='Safihalar')),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('abstract', models.TextField(max_length=3000, verbose_name='Abstrakt')),
                ('keywords', models.TextField(max_length=3000, verbose_name="Kalit so'zlar")),
                ('file', models.FileField(upload_to='article_files/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authors', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Mualliflar')),
                ('editor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journals.editor', verbose_name='Tahrirlovchi')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journals.journal', verbose_name='Jurnal')),
                ('references', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.references', verbose_name='Referens')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
